# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 923e24391e5ddc3edf3279851d90856bf99abcdb2eb8796fedeeb724737fbbc983fa72b558718ab28e2ad08ca970e111c286993ec23ac9867dbd6dddb3448dd5

test:
  secret_key_base: 6694f7f75b1893239af293ca497622f0a3e22539cc6b739dee71fedc966bc513ca03b2d8806931d19dd639c91760ed4ba13cddf1f73b77c36fbd60bd4697dfce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
